# paths
data: "emotions/full_data.csv"
# training
modelname: "bert-base-uncased"
lr: 0.00005
batch_size: 32
epochs: 3
split: 0.2
shuffle: true
num_workers: 0
pin_memory: true

# tokenizer
padding: true
truncation: true


#-------------------------------
output_dir: "./results"
per_device_train_batch_size: 32
per_device_eval_batch_size: 16
warmup_steps: 500                
weight_decay: 0.01             
logging_dir: './logs'            
logging_steps: 10
  