# paths
data: "src/resources/emotions/full_data.csv"
# training
modelname: "bert-base-uncased"
lr: 0.00005
batch_size: 16
loss_plot_step: 15
loss_plot_test_step: 12
acc_plot_step: 35
epochs: 3
split: 0.2
shuffle: true
num_workers: 0
pin_memory: true

# tokenizer
padding: true
truncation: true

#-------------------------------
output_dir: "./results"
per_device_train_batch_size: 5
per_device_eval_batch_size: 5
warmup_steps: 500                
weight_decay: 0.01             
logging_dir: './logs'            
logging_steps: 10



#-------------------------------------
# GO EMOTIONS META-DATA MAPPING
#-------------------------------------
# key: emotions, value: meta label
meta_mapping: {9: 0, 17: 1, 22: 2, 4: 3, 18: 4, 11: 0, 2: 1, 14: 2, 7: 3, 6: 4, 23: 0, 5: 1, 21: 2, 3: 3, 24: 4, 10: 0, 20: 1, 8: 2, 16: 3, 1: 4, 19: 0, 15: 1, 13: 2, 0: 3, 12: 4}
task_mapping: {1: [9, 17, 22, 4, 18], 2: [11, 2, 14, 7, 6], 3: [23, 5, 21, 3, 24], 4: [10, 20, 8, 16, 1], 5: [19, 15, 13, 0, 12]}