# paths
data: "src/resources/emotions/full_data.csv"
# training
modelname: "bert-base-uncased"
lr: 0.00003
batch_size: 8
loss_plot_step: 15
loss_plot_test_step: 12
acc_plot_step: 35
epochs: 3
split: 0.2
shuffle: true
num_workers: 4
pin_memory: true
train_num_samples: 100000 # set to -1 for all datapoints, otherwise specify a number
max_text_length: {'ag_news':128,'dbpedia_14':128,'yahoo_ans':256,'yelp_review':128}
train_meta_dataset: ['ag_news','dbpedia_14','yahoo_ans']
test_meta_dataset: ['yelp_review']

# Validation & test
val_step: 6000

test_num_samples: -1 # Change this if necessary

# tokenizer
padding: true
truncation: true

#-------------------------------
output_dir: "./results"
per_device_train_batch_size: 5
per_device_eval_batch_size: 5
warmup_steps: 1000
weight_decay: 0.01             
logging_dir: './logs'            
logging_steps: 10



#-------------------------------------
# GO EMOTIONS META-DATA MAPPING
#-------------------------------------
# key: emotions, value: meta label
meta_mapping: {9: 0, 17: 1, 22: 2, 4: 3, 18: 4, 11: 0, 2: 1, 14: 2, 7: 3, 6: 4, 23: 0, 5: 1, 21: 2, 3: 3, 24: 4, 10: 0, 20: 1, 8: 2, 16: 3, 1: 4, 19: 0, 15: 1, 13: 2, 0: 3, 12: 4}
task_mapping: {1: [9, 17, 22, 4, 18], 2: [11, 2, 14, 7, 6], 3: [23, 5, 21, 3, 24], 4: [10, 20, 8, 16, 1], 5: [19, 15, 13, 0, 12]}

#-------------------------------------
# Topic
#-------------------------------------
prepend_topic: 'This text is about '
prepend_review: 'All in all, it was '

# Datasets:
dataset_name: 'yahoo_ans' # use key to select dataset,

# NOTE: The keys should be all lowercase whereas values can be any string.
#--------------------------------------
# AG NEWS (key: ag_news)
#--------------------------------------
agnews_cache_dir: 'src/resources/ag_news'
agnews_remapping: {'sci/tech': 'science or technology'}


#--------------------------------------
# DBPedia 14 (key: dbpedia_14)
#--------------------------------------
dbpedia_cache_dir: 'src/resources/dbpedia_14'
dbpedia_remapping: {"educationalinstitution": "educational institution",
            "officeholder": "office holder",
            "meanoftransportation": "mean of transportation",
            "naturalplace": "natural place",
            "written work": "written work"}

#--------------------------------------
# Yahoo (key: yahoo_ans)
#--------------------------------------
yahoo_cache_dir: 'src/resources/yahoo_ans'
yahoo_remapping: {'society & culture':'Society','science & mathematics':'Science','health':'Health','education & reference':'Education'
,'computers & internet':'Computer','sports':'Sport','business & finance':'Business','entertainment & music':'Entertainment',
'family & relationships':'Relationship','politics & government':'Politics'}

#--------------------------------------
# Yelp review (key: yelp_review)
#--------------------------------------
yelp_cache_dir: 'src/resources/yelp_review'
yelp_remapping: {'1 star':'terrible','2 star':'bad','3 stars':'okay','4 stars':'good','5 stars':'great'}
